apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2019-03-23T19:47:18Z
  generation: 1
  labels:
    run: invillia-app
  name: invillia-app
  namespace: default
  resourceVersion: "100516"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/invillia-app
  uid: 77ab235e-4da4-11e9-bff2-025000000001
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: invillia-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: invillia-app
    spec:
      containers:
        - image: jclaudiocf/invillia:latest
          imagePullPolicy: Always
          name: invillia-app
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: 2019-03-23T19:47:18Z
      lastUpdateTime: 2019-03-23T19:47:18Z
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: 2019-03-23T19:47:18Z
      lastUpdateTime: 2019-03-23T19:47:24Z
      message: ReplicaSet "invillia-app-fbccf64bb" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2019-03-23T19:59:33Z
  labels:
    run: invillia-app
  name: invillia-service
  namespace: default
  resourceVersion: "101368"
  selfLink: /api/v1/namespaces/default/services/invillia-service
  uid: 2d5e5eb1-4da6-11e9-bff2-025000000001
spec:
  clusterIP: 10.96.154.188
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 31166
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: invillia-app
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - hostname: localhost